# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c9687b07fc9d0f3c180a12861ce365332a8d26a9a0fc7c5331d5096e4d5426237cdb3b6b5a974f34818f318b8b90e45d9b75ae9220d97253e1b896b71d37af

test:
  secret_key_base: ad00121425296f62255b62384333b7a493b30a180ac9013c3a9c2726dc037615ef69048b349bcb7214fc2247be9faa941378328da6ba2a7da0a3d25c643868d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
